(defun find-subsequence (mainstr substr)
  (let ((main-len (length mainstr))
        (sub-len (length substr)))
    (find-if (lambda (i)
               (every (lambda (j)
                        (char-equal (char mainstr (+ i j))
                                    (char substr j)))
                      (iota sub-len)))
             (iota (1+ (- main-len sub-len))))))
